# Generated by Django 5.2.8 on 2025-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
